site_name: Tomb Manual
site_url: https://dyne.org/docs/tomb

theme:
  name: material
  logo: images/dyneorg.svg
  favicon: images/favicon.png

extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md
  - Manpage: manpage.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
