site_name: CJIT Manual
site_url: https://dyne.org/docs/cjit
copyright: CJIT Manual written by <a href="https://jaromil.dyne.org">Jaromil</a>, Copyright &copy; 2024 Dyne.org Foundation

theme:
  name: material
  logo: images/dyneorg.svg
  favicon: images/favicon.png
  features:
    - content.tabs.link

extra:
 social:
    - icon: fontawesome/brands/github
      link: https://github.com/dyne/cjit
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/dyne-org/
 generator: false

#extra_css:
#  - stylesheets/extra.css

nav:
  - Introduction: index.md
  - Graphics: graphics.md
  - FAQ: faq.md
  - Builtin extensions: builtins.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
